version: '3.8'

services:

  jobmanager:
    build: .
    container_name: jobmanager
    ports:
      - "8081:8081"
      - "9249:9249"   # 🔥 Prometheus metrics
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_PROPERTIES=metrics.reporter.prom.class=org.apache.flink.metrics.prometheus.PrometheusReporter;metrics.reporter.prom.port=9249
    volumes:
      - .:/opt/flink/usrlib

  taskmanager:
    build: .
    container_name: taskmanager
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - taskmanager.numberOfTaskSlots=4
      - FLINK_PROPERTIES=metrics.reporter.prom.class=org.apache.flink.metrics.prometheus.PrometheusReporter;metrics.reporter.prom.port=9249

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: NfNerTIcRb-JsLgdWHloHA

  dashboard:
    build: .
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    command: streamlit run dashboard.py

  # 🔥 NEW SERVICE: PROMETHEUS
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml